#!/bin/bash

#1
log_file="$HOME/work3.log"
sudo cat /etc/passwd | awk -F: '{print "user "$1" has id "$3}' > "$log_file"

#2
sudo chage -l root | awk -F: 'NR==1{print "Last change of root password:"$2}' >> "$log_file"

#3
cat /etc/group | awk -F: '{print $1}' | sed -z 's/\n/, /g; s/, $/\.\n/g; s/^/Groups: /' >> "$log_file"

#4
sudo echo "Be careful!" | tee "/etc/skel/readme.txt" &> "/dev/null"

#5
sudo adduser u1 -p "6DhJnJaUDVTtA"

#6
sudo groupadd "g1"

#7
sudo usermod -G g1 u1

#8
id u1 >> "$log_file"

#9
sudo usermod -G g1 user

#10
getent group g1 | awk -F: '{print "g1 group users: "$4}' | sed s/'\,'/', '/g

#11
sudo chsh --shell "/usr/bin/mc" u1

#12
sudo adduser u2 -p "SqItAxZ6.tATY"

#13
test13_dir="/home/test13"
sudo mkdir "$test13_dir"
sudo cp "$log_file" "$test13_dir/work3-1.log"
sudo cp "$log_file" "$test13_dir/work3-2.log"

#14
sudo chown -R u1:u2 "$test13_dir"
sudo chmod 640 "$test13_dir"/*
sudo chmod 751 "$test13_dir"

#15
test14_dir="$HOME/test14"
mkdir "$test14_dir"
chmod 1777 "$test14_dir"
sudo chown u1:"$USER" "$test14_dir"
chmod 701 "$HOME"

#16
cp "/bin/nano" "$test14_dir"
chmod 4111 "$test14_dir/nano"
sudo chown u1: "$test14_dir/nano"

#17
test15_dir="$HOME/test15"
mkdir "$test15_dir"
echo "vires in numeris" > "$test15_dir/secret_file"
chmod 444 "$test15_dir/secret_file"
chmod 111 "$test15_dir"
